global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'hagrid-stag'
    scrape_interval: 5s
    scheme: "http"
    metrics_path: "/metrics"
    static_configs:
      - targets: ['192.168.247.162:3001','192.168.140.39:3001']
